[build]
# The index HTML file to drive the bundling process.
target = "index.html"
# Build in release mode.
release = false
# The output dir for all final assets.
dist = "dist"
# The public URL from which assets are to be served.
public_url = "/"
# Whether to include hash values in the output file names.
filehash = true

[serve]
# The address to serve on.
address = "127.0.0.1"
# The port to serve on.
port = 8080
# Open a browser tab once the initial build is complete.
open = true
# Disable auto-reload of the web app.
no_autoreload = false

[tools]
# Default wasm-bindgen version to download.
wasm_bindgen = "0.2.83"
# Default wasm-opt version to download.
wasm_opt = "version_110"

[[proxy]]
backend = "https://api.followingpilots.com/api/user/public"
